version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/asutus.api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development